# Generated by Django 4.2.3 on 2023-08-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
